name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openbikesensor/openbikesensorflasher:${GITHUB_RUN_NUMBER}

    - name: KICS Github Action - just for testing - not official
      uses: fjsnogueira/kics-github-action@v1.4
      with:
        path: .
